language: python
python:
  - "2.7"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - sudo docker-compose -f test/travis_ci_scripts/docker-compose.yml pull
  - sudo docker-compose -f test/travis_ci_scripts/docker-compose.yml up -d
  - python -m unittest discover
