language: python
dist: xenial
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
services:
  - docker
install:
  - pip install NebulaPythonSDK
script:
  - sudo sh test/travis_ci_scripts/travis_ci_build_script.sh
  - python -m unittest discover
deploy:
  provider: pypi
  user: naorlivne
  password:
    secure: SxcnVy5rN996xry9WQLCXPjCPS5tjX6d7f1AjRdGmILLEHfyXtD7U3XgIoQfxOddasqfplYE2J4l8XGDcnPr52/y1Zh8ZT2flm+6LcP1EFpe4qMn8+1znsny851t7eZowEpfrqdRUcxGXPewyz3DXNU8dz0rmn7cVz0blKxQOhw7bqZbq42SJGXp0y87xB7CFxJOuJ7AR5riKAwj/j7wQU3cYF20BbAXTi9P6+TrDgq/a+0YDjYm2vMyHeEsi2U/27m8haG50TibufTBszL1jrfQyP02tjASvMrXMJVrjJYGtcF1upT46b2DnkzQ+fXm4QrySvWHSmkCK1jP4KsUY+qnEb8AU4Ag+Zro7B33uQezPkvpQyBPzP3LM3bLD5a29dAnLeJ4sX3b6yj+bylHBhNU460HOnxpOaS1J280p+ZTCH8Pq5cPf51J2e8TOCCFPOhqLa/1WGG6XI1Vjvx00kPPci/MWMEKiLg3Q2eJyTTiKKJMdsIrjNMT+i1KYuBine4Xq3k9HcavsufJJ2ZBVntO6IYMW4t5hq+zkT55ESQAoLN/BzDXpJHb50kB/sDnrIq7/oL2KMxW4I4xzqN2usUUisI09hs3NOt3lcbh6dugPm6yFYAXtjmCTbO6gLWVTiKH8OHoWc43xmc6DfLegwuYdXeXYIEvXUS1nXDe6aM=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    python: '3.7'
